name: staging-release

on:
  push:
    branches:
      - main

concurrency:
  group: staging-release

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v3

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install go-task
        run: wget -c https://github.com/go-task/task/releases/download/v3.36.0/task_linux_amd64.tar.gz -O - | tar -xz -C /usr/local/bin/

      - uses: actions/checkout@v4

      - name: Install Snowflake CLI
        run: pip install snowflake-cli-labs

      - name: Install SnowSQL
        run: |
        wget -cqO- https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowflake-snowsql-1.2.32-1.x86_64.rpm -O snowflake-snowsql.rpm
        sha256sum snowflake-snowsql.rpm | sha256sum --check 71ae69821279da7a08be99a4980077a0fa8768e13d64b68fc868f5a37ef3752f
        rpm -i snowflake-snowsql.rpm

      - name: Run task
        run: |
        task foo
        snow --help
        snowsql --help