name: staging-release

on:
  push:
    branches:
      - main

concurrency:
  group: staging-release

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Docker Buildx 
        uses: docker/setup-buildx-action@v3
      - name: Install go-task
        run: wget -c https://github.com/go-task/task/releases/download/v3.36.0/task_linux_amd64.tar.gz -O - | tar -xz -C /usr/local/bin/
      - name: Run task
        run: task foo